dist: bionic
language: ruby
rvm:
  - "2.5"
sudo: false
cache: bundler
script:
  - |
    if grep -rEi "^wiki_[^ ]+: " source/; then
      echo '/!\ Wiki headers are obsolete (see previous log entries)'
      exit 2
    fi
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external --allow-hash-href --empty-alt-ignore
